# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: bionic  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - peckama2@fel.cvut.cz
env:
  global:
    - ROS_DISTRO=melodic
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO=melodic

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh