%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-robot-body-filter
Version:        1.1.5
Release:        1%{?dist}
Summary:        ROS robot_body_filter package

License:        BSD
URL:            https://github.com/peci1/robot_body_filter
Source0:        %{name}-%{version}.tar.gz

Requires:       fcl-devel
Requires:       pcl-devel
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-filters
Requires:       ros-melodic-geometric-shapes
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-laser-geometry
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-moveit-core
Requires:       ros-melodic-moveit-ros-perception
Requires:       ros-melodic-pcl-conversions
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf2
Requires:       ros-melodic-tf2-ros
Requires:       ros-melodic-urdf
Requires:       ros-melodic-visualization-msgs
BuildRequires:  fcl-devel
BuildRequires:  pcl-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-filters
BuildRequires:  ros-melodic-geometric-shapes
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-laser-geometry
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-moveit-core
BuildRequires:  ros-melodic-moveit-ros-perception
BuildRequires:  ros-melodic-pcl-conversions
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf2
BuildRequires:  ros-melodic-tf2-eigen
BuildRequires:  ros-melodic-tf2-ros
BuildRequires:  ros-melodic-tf2-sensor-msgs
BuildRequires:  ros-melodic-urdf
BuildRequires:  ros-melodic-visualization-msgs

%description
Filters the robot's body out of laser scans or point clouds.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Fri Nov 08 2019 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.5-1
- Autogenerated by Bloom

* Wed Aug 07 2019 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.4-1
- Autogenerated by Bloom

* Tue Aug 06 2019 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.3-1
- Autogenerated by Bloom

* Tue Jul 30 2019 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.2-1
- Autogenerated by Bloom

* Tue Jul 30 2019 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.1-0
- Autogenerated by Bloom

* Thu Jul 18 2019 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.0-1
- Autogenerated by Bloom

