%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-robot-body-filter
Version:        1.2.0
Release:        4%{?dist}%{?release_suffix}
Summary:        ROS robot_body_filter package

License:        BSD
URL:            https://github.com/peci1/robot_body_filter
Source0:        %{name}-%{version}.tar.gz

Requires:       pcl-devel
Requires:       ros-noetic-dynamic-reconfigure
Requires:       ros-noetic-fcl
Requires:       ros-noetic-filters
Requires:       ros-noetic-geometric-shapes
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-laser-geometry
Requires:       ros-noetic-message-runtime
Requires:       ros-noetic-moveit-core
Requires:       ros-noetic-moveit-ros-perception
Requires:       ros-noetic-pcl-conversions
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-sensor-msgs
Requires:       ros-noetic-std-msgs
Requires:       ros-noetic-tf2
Requires:       ros-noetic-tf2-ros
Requires:       ros-noetic-urdf
Requires:       ros-noetic-visualization-msgs
BuildRequires:  pcl-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-dynamic-reconfigure
BuildRequires:  ros-noetic-fcl
BuildRequires:  ros-noetic-filters
BuildRequires:  ros-noetic-geometric-shapes
BuildRequires:  ros-noetic-geometry-msgs
BuildRequires:  ros-noetic-laser-geometry
BuildRequires:  ros-noetic-message-generation
BuildRequires:  ros-noetic-moveit-core
BuildRequires:  ros-noetic-moveit-ros-perception
BuildRequires:  ros-noetic-pcl-conversions
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-rostest
BuildRequires:  ros-noetic-sensor-msgs
BuildRequires:  ros-noetic-std-msgs
BuildRequires:  ros-noetic-tf2
BuildRequires:  ros-noetic-tf2-eigen
BuildRequires:  ros-noetic-tf2-ros
BuildRequires:  ros-noetic-tf2-sensor-msgs
BuildRequires:  ros-noetic-urdf
BuildRequires:  ros-noetic-visualization-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Filters the robot's body out of laser scans or point clouds.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri Jul 30 2021 Martin Pecka <peckama2@fel.cvut.cz> - 1.2.0-4
- Autogenerated by Bloom

* Fri Jul 30 2021 Martin Pecka <peckama2@fel.cvut.cz> - 1.2.0-3
- Autogenerated by Bloom

* Fri Jul 30 2021 Martin Pecka <peckama2@fel.cvut.cz> - 1.2.0-2
- Autogenerated by Bloom

* Fri Jul 30 2021 Martin Pecka <peckama2@fel.cvut.cz> - 1.2.0-1
- Autogenerated by Bloom

* Sat Apr 17 2021 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.9-1
- Autogenerated by Bloom

* Mon Apr 12 2021 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.8-3
- Autogenerated by Bloom

* Mon Apr 12 2021 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.8-2
- Autogenerated by Bloom

* Mon Apr 12 2021 Martin Pecka <peckama2@fel.cvut.cz> - 1.1.8-1
- Autogenerated by Bloom

